[pytest]
# 1. 命令行参数配置
# -v: 打印详细运行日志信息
# -s: 允许终端在运行过程中输出 logger.info() 的内容
# --alluredir: 生成 allure 测试报告的原始 JSON 数据
# --clean-alluredir: 每次运行前清空上一次的旧报告数据，防止数据堆积
addopts = -vs --alluredir=./reports/allure_raw --clean-alluredir

# 2. 指定测试用例的默认执行目录 (精准制导，提升速度)
testpaths = ./tests

# 3. 改变默认的测试用例发现规则 (规范团队代码风格)
python_files = test_*.py
python_classes = Test*
python_functions = test_*

# 将当前项目根目录加入环境变量，解决导包找不到的问题
pythonpath = .

# 4. 注册自定义 Marker 标记 (用于筛选执行，如：pytest -m "smoke")
markers =
    smoke: 冒烟测试用例，用于提测前的核心功能快速验证
    p0: 核心业务链路用例
    p1: 异常边界测试用例
    db: 需要连接数据库进行断言的用例

filterwarnings =
    ignore::UserWarning:zhipuai.*
# 5. 日志中心配置 (开启实时终端日志输出，摆脱单纯的 logger.info)
;log_cli = true
;log_cli_level = INFO
;log_cli_format = %(asctime)s [%(levelname)s] %(filename)s:%(lineno)s | %(message)s
;log_cli_date_format = %Y-%m-%d %H:%M:%S